name: Quality Assurance

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Check directory contents
      run: ls -la

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
        
    - name: Run type checking
      run: bash dev_scripts/run_type_checking.sh
      
    - name: Run code formatting check
      run: bash dev_scripts/run_formatting.sh
      
    - name: Run tests
      run: bash dev_scripts/run_tests.sh